name: test_if_installed
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0-311.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/logo.png
  fonts:
    - family: neue
      fonts:
        - asset: assets/fonts/thin.otf
          weight: 300
        - asset: assets/fonts/bold.otf
          weight: 700
        - asset: assets/fonts/medium.otf
          weight: 500
          style: italic
    - family: rustico
      fonts:
        - asset: assets/fonts/rustico.otf
